### ISSUE TITLE
Error when trying to print the stacktrace of an action error when the thrown exception contains a null message

### ISSUE THREAD

**Issue by yottta** [entzik/status-machina#1]
When a transition is triggered and an action is executed, if in the executed action a NPE (or any other exception that does not contain a message) occurs the internal error handling is crashing resulting in loosing stacktrace of the underlying error.
`java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at io.statusmachina.core.stdimpl.MachineInstanceImpl.applyErrorState(MachineInstanceImpl.java:290)
	at io.statusmachina.core.stdimpl.MachineInstanceImpl.lambda$applyTransition$7(MachineInstanceImpl.java:281)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.statusmachina.core.stdimpl.MachineInstanceImpl.applyTransition(MachineInstanceImpl.java:273)
	at io.statusmachina.core.stdimpl.MachineInstanceImpl.lambda$tryStp$3(MachineInstanceImpl.java:221)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.statusmachina.core.stdimpl.MachineInstanceImpl.tryStp(MachineInstanceImpl.java:218)
	at io.statusmachina.core.stdimpl.MachineInstanceImpl.applyTransition(MachineInstanceImpl.java:285)
	at io.statusmachina.core.stdimpl.MachineInstanceImpl.lambda$tryStp$3(MachineInstanceImpl.java:221)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.statusmachina.core.stdimpl.MachineInstanceImpl.tryStp(MachineInstanceImpl.java:218)
	at io.statusmachina.core.stdimpl.MachineInstanceImpl.start(MachineInstanceImpl.java:147)`

**Comment by entzik** [comment]
thanks !
